logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: create
  config:
    import:
      - classpath:/oauth2-config/application.yml
